#!/bin/bash
. ./shellunit.sh
. ./testhelpers.sh

setup()
{
    rm -f alarm
    touch alarm
    rm -f wakeup
    touch wakeup
}

teardown()
{
    rm -f alarm
    rm -f wakeup
}

export ACPI_ENABLED=yes
export WAKEALARM=./alarm
export WAKEUP_FILE=./wakeup
export FAKEDATETIME="2008-01-01 00:00:00"
export TZ="Europe/Berlin"

echo "Running Tests:"

start_test "Should not do anything when disabled"
    ACPI_ENABLED=no \
      bash ./testwakeup `wakeuptime '2008-05-11 20:00:00'`
    alarm=`cat ./alarm`
    assert_equals "" "$alarm"
end_test

start_test "Should disable wakeup when no timer is set"
    bash ./testwakeup `wakeuptime '@0'`
    alarm=`cat ./alarm`
    assert_equals "$alarm" "0"
end_test

start_test "Should wake up ACPI_START_AHEAD minutes ahead"
    ACPI_START_HEAD=8 \
      bash ./testwakeup `wakeuptime '2008-05-11 20:00:00'`
    expect_wakeup_time "2008-05-11 19:55:00"
end_test

start_test "Should wake up daily at 03:00 today"
    ACPI_REGULAR_DAYS="1 2 3 4 5 6 7" \
    ACPI_REGULAR_TIME="03:00" \
      bash ./testwakeup `wakeuptime '2008-05-12 20:00:00'`
    expect_wakeup_time "2008-01-01 02:55:00"
end_test

start_test "Should write seconds delta since 1970-01-01 to WAKEALARM"
    ACPI_ALARM=/does-not-exist \
    WAKEALARM=./alarm \
      bash ./testwakeup `wakeuptime '2008-05-11 20:00:00'`
    expect_wakeup_time '2008-05-11 19:55:00' `cat ./alarm`
end_test

start_test "Should write the wakeup time to the wakeup file"
    bash ./testwakeup `wakeuptime '2008-05-11 20:00:00'`
    expect_wakeup_file "2008-05-11 19:55:00"
end_test

export FAKEDATETIME="2008-01-01 02:00:00"
start_test "Should wake up daily at 01:00 tomorrow"
    ACPI_REGULAR_DAYS="1 2 3 4 5 6 7" \
    ACPI_REGULAR_TIME="01:00" \
      bash ./testwakeup `wakeuptime '2008-05-12 20:00:00'`
    expect_wakeup_time "2008-01-02 00:55:00"
end_test

export FAKEDATETIME="2008-05-11 01:00:00"
start_test "Should wake up on Monday 2:00 when shutting down on Sunday 01:00"
    # 2008-05-11 = Sunday
    ACPI_REGULAR_DAYS="1 4" \
    ACPI_REGULAR_TIME="02:00" \
      bash ./testwakeup `wakeuptime '@0'`
    expect_wakeup_time "2008-05-12 01:55:00"
end_test

export FAKEDATETIME="2008-05-11 01:00:00"
start_test "Should wake up on Monday 2:00 when shutting down on Monday 01:00"
    # 2008-05-11 = Sunday
    ACPI_REGULAR_DAYS="1 4" \
    ACPI_REGULAR_TIME="02:00" \
      bash ./testwakeup `wakeuptime '@0'`
    expect_wakeup_time "2008-05-12 01:55:00"
end_test

export FAKEDATETIME="2008-05-13 01:00:00"
start_test "Should wake up on Thursday 2:00 when shutting down on Tuesday 01:00"
    # 2008-05-11 = Sunday
    ACPI_REGULAR_DAYS="1 4" \
    ACPI_REGULAR_TIME="02:00" \
      bash ./testwakeup `wakeuptime '@0'`
    expect_wakeup_time "2008-05-15 01:55:00"
end_test

export FAKEDATETIME="2026-01-01 00:00:00"
start_test "Should wake up on Friday 23:55 when shutting down on Wednesday 00:00"
    # 2008-05-11 = Sunday
    ACPI_MAX_MARGIN_HOURS=48 \
      bash ./testwakeup `wakeuptime '@0'`
    expect_wakeup_time "2026-01-02 23:55:00"
end_test

export FAKEDATETIME="2026-01-01 00:00:00"
start_test "Should wake up on Friday 23:55 when shutting down on Wednesday 00:00"
    # 2008-05-11 = Sunday
    ACPI_MAX_MARGIN_HOURS=48 \
    ACPI_REGULAR_DAYS="5" \
    ACPI_REGULAR_TIME="02:00" \
      bash ./testwakeup `wakeuptime '@0'`
    expect_wakeup_time "2026-01-02 01:55:00"
end_test

exit $FAILURE
